/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      spacing: {
        px: "1px",
        0: "0px",
        0.5: "calc(var(--spacing) * 0.5)",
        1: "calc(var(--spacing) * 1)",
        1.5: "calc(var(--spacing) * 1.5)",
        2: "calc(var(--spacing) * 2)",
        2.5: "calc(var(--spacing) * 2.5)",
        3: "calc(var(--spacing) * 3)",
        3.5: "calc(var(--spacing) * 3.5)",
        4: "calc(var(--spacing) * 4)",
        5: "calc(var(--spacing) * 5)",
        6: "calc(var(--spacing) * 6)",
        7: "calc(var(--spacing) * 7)",
        8: "calc(var(--spacing) * 8)",
        9: "calc(var(--spacing) * 9)",
        10: "calc(var(--spacing) * 10)",
        11: "calc(var(--spacing) * 11)",
        12: "calc(var(--spacing) * 12)",
        14: "calc(var(--spacing) * 14)",
        16: "calc(var(--spacing) * 16)",
        20: "calc(var(--spacing) * 20)",
        24: "calc(var(--spacing) * 24)",
        28: "calc(var(--spacing) * 28)",
        32: "calc(var(--spacing) * 32)",
        36: "calc(var(--spacing) * 36)",
        40: "calc(var(--spacing) * 40)",
        44: "calc(var(--spacing) * 44)",
        48: "calc(var(--spacing) * 48)",
        52: "calc(var(--spacing) * 52)",
        56: "calc(var(--spacing) * 56)",
        60: "calc(var(--spacing) * 60)",
        64: "calc(var(--spacing) * 64)",
        72: "calc(var(--spacing) * 72)",
        80: "calc(var(--spacing) * 80)",
        96: "calc(var(--spacing) * 96)",
      },
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
